version: '3.4'
services:
  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    logging:
      options:
        max-size: 10m
        max-file: "3"
    healthcheck:
      # test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

# docker exec -it postgres psql -U admin  